services:
  postgres:
    restart: always
    image: 'postgres:16.6-alpine'
    environment:
      POSTGRES_PASSWORD: postgres_password
#    ports:
#      - '5433:5432'
  redis:
    image: 'redis:latest'
#    ports:
#      - '6380:6379'
  nginx:
    restart: always
    depends_on:
      - api
      - client
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    restart: always
    depends_on:
      - postgres
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server/src:/usr/app/src
    environment:
      CHOKIDAR_USEPOLLING: true
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: postgres_password
  client:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client/src:/usr/app/src
    environment:
      CHOKIDAR_USEPOLLING: true
      WDS_SOCKET_PORT: 0
  worker:
    restart: always
    depends_on:
      - postgres
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - ./worker/src:/usr/app/src
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
